baseURL = 'https://fitterhmp11.github.io'
languageCode = 'en-us'
title = 'Fitterhmp11 Development Blog'
theme = 'ananke'

# Configure the main page content
[params]
 mainSections = ["posts"]   

# only show posts, not about from the homepage
# authorGitHub = "https://github.com/fitterhmp11/public" 
# GitHub link for author.



[[menu.main]]

  name = "About"
  url = "/about"
  weight = 2




[[menu.main]]

  name = "Development"
  url = "/categories/Development"
  weight = 4

  

# [params.ananke.social.github]
# username = "fitterhmp11/public"


